[project]
name = "chronetic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "northernmarshes", email = "northernmarshes@gmail.com" }]
requires-python = ">=3.14"
dependencies = [
    "mpremote>=1.29.0",
    "network>=0.1",
]

# [project.scripts]
# chronetic = "chronetic:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "tests/fetch_data",
]
